### ISSUE TITLE
List for speakers

### ISSUE THREAD

**Issue by ava517** [papers-we-love/taipei#5]
Hi @oskarth
Should a waiting list be created for speakers? If any contributors or speakers who're interested in giving a presentation, they can fork this repository and fill out their names/ given titles. Likewise, we can also generate the form if there's anyone with whom we met at conferences or meetups interested in presenting. It would be helpful.

**Comment by oskarth** [comment]
Not sure we have enough people interested to have a wait list 😂 

Have you heard about someone wanting to speak but not knowing how?

Maybe this Telegram invite link is enough for now? https://github.com/papers-we-love/taipei#contact

**Comment by ava517** [comment]
Haha... sounds right.

I have a young 😂AI research student who always come to me to ask about Ethereum stuffs and events. Thinking he is really passionate about your works and is willing to give a talk. I will have him join your group per your authorization. 

Thanks for the advice @oskarth
